### ISSUE TITLE
highlighting on hover

### ISSUE THREAD

**Issue by adammertel** [adammertel/dpp-mapApp#12]

**Comment by MarkusBreier** [comment]
It would be nice, if you get a preview of the objects name, if you hover over an object in the map window. that would be especially useful for clusters.

**Comment by adammertel** [comment]
![image](https://cloud.githubusercontent.com/assets/12932677/22327838/89e2b224-e3b9-11e6-8fe4-50487ba1e843.png)

**Comment by MarkusBreier** [comment]
That's perfect!
