### ISSUE TITLE
links binded to right side of footer

### ISSUE THREAD

**Issue by adammertel** [adammertel/dpp-mapApp#13]

**Comment by adammertel** [comment]
@MarkusBreier what links should be binded to those buttons (Imprint, Team, Contact)?

**Comment by MarkusBreier** [comment]
Remove the Team-Button

Contact: Mailto-Link: info.dpp@oeaw.ac.at

Imprint should open a Popup containing the following Information: 

University of Vienna, Department of Geography and Regional Reserach
Universitaetsstr. 7
1010, Vienna, Austria

Digitising Patterns of Power is a project funded by the Austrian Academy of Sciences program "Digitales kulturelles Erbe".

**Comment by adammertel** [comment]
Imprint details will be checked with Alex

**Comment by MarkusBreier** [comment]
I think that we can put the imprint and contact into one pop-up.

**Comment by adammertel** [comment]
@MarkusBreier and what will be the label for this pop-up?

**Comment by MarkusBreier** [comment]
**Digitising Patterns of Power is a project funded by the Austrian Academy of Sciences program "Digitales kulturelles Erbe".**

Project Homepage: http://dpp.oeaw.ac.at/
Contact: info.dpp@oeaw.ac.at

**Involved Institutions:**
**IMAFO Institute for Medieval Research, Austrian Academy of Sciences **
Hollandstraße 11-13
1020 Vienna, Austria

**University of Vienna, Department of Geography and Regional Reserach**
Universitaetsstr. 7
1010 Vienna, Austria

**Comment by adammertel** [comment]
perfect. And label - "**Imprint and Contact**" ?

**Comment by MarkusBreier** [comment]
Yes

**Comment by adammertel** [comment]
![image](https://cloud.githubusercontent.com/assets/12932677/22287878/dc154504-e2f4-11e6-80dc-8619025bf03e.png)

**Comment by MarkusBreier** [comment]
perfect
