### ISSUE TITLE
set maximal extent for map

### ISSUE THREAD

**Issue by adammertel** [adammertel/dpp-mapApp#15]
@MarkusBreier could you please provide this extent coordinates?

**Comment by adammertel** [comment]
minX = -12,98°   maxX = 71,38°
minY = 27,45°    maxY = 60,97°

**Comment by DanielNell** [comment]
@adammertel please set the minimum zoom to zoom level 5 (currently it is zoom level 2)

**Comment by adammertel** [comment]
@DanielNell I will create a mapOptions.json file, where all these values could be set, ok?

**Comment by DanielNell** [comment]
@adammertel perfect
