### ISSUE TITLE
Welcome window discussion

### ISSUE THREAD

**Issue by adammertel** [adammertel/dpp-mapApp#16]
Do we need this window?
Is it possible to use it as a tutorial or somehow?
![image](https://cloud.githubusercontent.com/assets/12932677/22291546/40b1ce80-e307-11e6-83a9-33ea5772db83.png)

**Comment by MarkusBreier** [comment]
I think we can leave it as it is for now.

**Comment by adammertel** [comment]
added WELCOMEWINDOW_SHOW variable so window could be turned off with appoptions.json config file.
