### ISSUE TITLE
Move data to separate folder on server

### ISSUE THREAD

**Issue by MarkusBreier** [adammertel/dpp-mapApp#20]

**Comment by adammertel** [comment]
two config files created:
* mapbaselayers.json
* mapoverlayers.json

**Comment by adammertel** [comment]
Created config files:
* **appoptions.json** - general settings, at this moment there are only few variables to set welcome window
* **appstyle.json** - dynamic general styling
* **casestudies.json** - defining labels and spatial extent for case studies
* **mapbaselayers.json** - base layers
* **mapoptions.json** - setting map (zoom levels, etc)
* **mapoverlayers.json** - wms/geojson additional layers
* **mapvisuals.json** - visual styling of map items
* **timeoptions.json** - defining values for time-slider

This config files are based on the current state of the application, therefore more variables will be added during the development. If you miss there something now, please let me know. 
I will also try to add a basic **documentation** (#23).
