### ISSUE TITLE
Case Study selector should be similar to other buttons in header

### ISSUE THREAD

**Issue by MarkusBreier** [adammertel/dpp-mapApp#29]

**Comment by adammertel** [comment]
![image](https://cloud.githubusercontent.com/assets/12932677/22501639/fc4ddc9e-e869-11e6-85d7-08e71a676057.png)

**Comment by adammertel** [comment]
![image](https://cloud.githubusercontent.com/assets/12932677/22518327/7c1215b6-e8ac-11e6-9e84-d21919576714.png)

**Comment by MarkusBreier** [comment]
Can you also add an icon to the selection?
Maybe 
![image](https://cloud.githubusercontent.com/assets/25224392/22541294/d2d8b4f8-e925-11e6-9ef9-da4b5de5fac9.png)

or

![image](https://cloud.githubusercontent.com/assets/25224392/22541313/e6f89e4e-e925-11e6-94df-e2141bcd50b1.png)
