### ISSUE TITLE
unselecting selected feature

### ISSUE THREAD

**Issue by adammertel** [adammertel/dpp-mapApp#4]

**Comment by adammertel** [comment]
![image](https://cloud.githubusercontent.com/assets/12932677/22113288/0b2f60c4-de66-11e6-95fc-92d0006dafbe.png)

**Comment by MarkusBreier** [comment]
Looks good. X should be top right.

![screenshot 4](https://cloud.githubusercontent.com/assets/25224392/22114379/87ed5910-de69-11e6-9b06-97f57dbe09aa.png)

**Comment by adammertel** [comment]
ok, I moved it even more to top-right. Will be uploaded in the next few minutes

![image](https://cloud.githubusercontent.com/assets/12932677/22115415/2fb16aa8-de6d-11e6-90c2-679665335aa5.png)
