### ISSUE TITLE
defined cluster color and size

### ISSUE THREAD

**Issue by adammertel** [adammertel/dpp-mapApp#7]

**Comment by adammertel** [comment]
is this sufficient?
![image](https://cloud.githubusercontent.com/assets/12932677/22325760/e9a89cc8-e3af-11e6-8d06-c96a519d0fc9.png)

**Comment by MarkusBreier** [comment]
Can you make it in a neutral grey?

**Comment by adammertel** [comment]
I do not think, this is the good way to go... ![image](https://cloud.githubusercontent.com/assets/12932677/22326517/5615ac04-e3b3-11e6-968b-241d9e377afa.png)

**Comment by MarkusBreier** [comment]
You are right. Maybe make the red/orange a little bit more restrained.

**Comment by adammertel** [comment]
could you please send me the color value?

**Comment by MarkusBreier** [comment]
What color value did you use?

**Comment by adammertel** [comment]
rgba(130, 130, 130, .6)

**Comment by adammertel** [comment]
rgba(254, 85, 6, .6)

**Comment by MarkusBreier** [comment]
How about (240,100,15,6) ?

**Comment by adammertel** [comment]
![image](https://cloud.githubusercontent.com/assets/12932677/22328066/996a8fcc-e3ba-11e6-860e-86cf0477948a.png)
